// <auto-generated />
namespace TiendaEnLinea.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class nullablePrecioOferta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullablePrecioOferta));
        
        string IMigrationMetadata.Id
        {
            get { return "202011012200187_nullablePrecioOferta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
